//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YazilimSinamaEntities : DbContext
    {
        public YazilimSinamaEntities()
            : base("name=YazilimSinamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBelgeler> tblBelgeler { get; set; }
        public virtual DbSet<tblDemirbas> tblDemirbas { get; set; }
        public virtual DbSet<tblDemirbasTuru> tblDemirbasTuru { get; set; }
        public virtual DbSet<tblDepartman> tblDepartman { get; set; }
        public virtual DbSet<tblFakulte> tblFakulte { get; set; }
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblOda> tblOda { get; set; }
        public virtual DbSet<tblOdaDemirbasAtama> tblOdaDemirbasAtama { get; set; }
        public virtual DbSet<tblPersonel> tblPersonel { get; set; }
    }
}
