//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBelgeler
    {
        public int BelgeID { get; set; }
        public string BelgeAdi { get; set; }
        public System.DateTime BelgeOlusturulmaTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string BelgeYolu { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
    }
}
