//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDemirbas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDemirbas()
        {
            this.tblOdaDemirbasAtama = new HashSet<tblOdaDemirbasAtama>();
        }
    
        public int DemirbasID { get; set; }
        public string DemirbasAdi { get; set; }
        public string DemirbasKodu { get; set; }
        public decimal Fiyat { get; set; }
        public System.DateTime AlimTarihi { get; set; }
        public int DemirbasTuruID { get; set; }
        public int FakulteID { get; set; }
        public int DepartmanID { get; set; }
        public int Adet { get; set; }
    
        public virtual tblDemirbasTuru tblDemirbasTuru { get; set; }
        public virtual tblDepartman tblDepartman { get; set; }
        public virtual tblFakulte tblFakulte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOdaDemirbasAtama> tblOdaDemirbasAtama { get; set; }
    }
}
