//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOdaDemirbasAtama
    {
        public int OdaDemirbasAtamaID { get; set; }
        public Nullable<int> OdaID { get; set; }
        public Nullable<int> DemirbasID { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual tblDemirbas tblDemirbas { get; set; }
        public virtual tblOda tblOda { get; set; }
    }
}
