//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOda()
        {
            this.tblOdaDemirbasAtama = new HashSet<tblOdaDemirbasAtama>();
        }
    
        public int OdaID { get; set; }
        public string OdaAdi { get; set; }
        public int DepartmanID { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual tblDepartman tblDepartman { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOdaDemirbasAtama> tblOdaDemirbasAtama { get; set; }
    }
}
